# 파일명: content-web/all-in-one-web.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-web
  template:
    metadata:
      labels:
        app: content-web
    spec:
      containers:
        - name: content-web
          image: cnacrksws.azurecr.io/content-web:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: content-web-service
spec:
  selector:
    app: content-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

