# 파일명: .github/workflows/contoso-web.yml

name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: rg-modernapp
          cluster-name: cnaksksws
          subscription: ecec9459-db5c-44cd-be16-6d20c0558049

      - name: Deploy to AKS
        run: kubectl apply -f content-web/all-in-one-web.yaml

